### ISSUE TITLE
option `mpl-use-full-test-name` breaks hash library path

### ISSUE THREAD

**Issue by theRealSuperMario** [matplotlib/pytest-mpl#115]
See https://github.com/matplotlib/pytest-mpl/pull/114

It looks like the paths are not correctly adapted if `mpl-use-full-test-name` is enabled

See tests in PR

<img width="888" alt="image" src="https://user-images.githubusercontent.com/6517465/110247997-3b6c9000-7f6f-11eb-8037-858dcd91a028.png">

Test output is
>>> Can't find hash library ..

As far as I understand, the error can be narrowed down to 

https://github.com/matplotlib/pytest-mpl/blob/7bb5d44161cba8877f06565a4b850300afb87c42/pytest_mpl/plugin.py#L462

I will push a fix in https://github.com/matplotlib/pytest-mpl/pull/114 later.

**Comment by ConorMacBride** [comment]
From looking at #114, I think the fix was changing
```py
        hash_library_filename = (Path(item.fspath).parent / hash_library_filename).absolute()
```
to
```py
        if self.config.getini("mpl-use-full-test-name"):
            hash_library_filename = hash_library_filename.absolute()
        else:
            hash_library_filename = (Path(item.fspath).parent / hash_library_filename).absolute()
```

[As currently documented](https://pytest-mpl.readthedocs.io/en/latest/configuration.html#whether-to-include-the-module-name-in-the-filename), `mpl-use-full-test-name` should not affect the directory from where the hash library file is relative to. There is an issue with the hash library path, but I don't think it is related to the `mpl-use-full-test-name` option.

There is a separate issue (noted in #198) saying that `--mpl-hash-library` should be relative to where pytest was run (to match `--mpl-baseline-path`), which I think should solve this issue with the broken hash library path.
