### ISSUE TITLE
--mpl-results-always command not saving the results

### ISSUE THREAD

**Issue by Vital-Fernandez** [matplotlib/pytest-mpl#208]
Hi! I am pretty new to pytest and I wonder if I could ask here for advice.

I am run mpl tests succesfully on my pc but when I try to run it on circleci it fails. I want to undestand better how the baseline/results folder data comparison works

I have this configuration on my pyproject.toml:

```
[project]
name = "lime-stable"
version = "0.9.92"

[tool.pytest.ini_options]
pythonpath = ["src"]
mpl-baseline-path = 'tests/baseline'
```

IF I run the commmand:

`pytest tests --mpl --mpl-generate-path=tests/baseline
`
The images are generated correctly on the tests/baseline folder

If I run the command:

`pytest tests --mpl
`
All the tests are succesful

However if I run the command:

`pytest tests --mpl --mpl-results-always
`
The results images are not saved. 

I wonder if anyone could help with a diagnostic to find the solution. I am using python 3.9 in windows 11 with:

```
pytest                        7.4.2
pytest-cov                    4.1.0
pytest-mpl                    0.16.1
```

Thanks

**Comment by ConorMacBride** [comment]
Welcome @Vital-Fernandez! The result images are written to a temporary directory by default, which can be hard to find. Try setting a different directory with this option: https://pytest-mpl.readthedocs.io/en/latest/configuration.html#directory-to-write-testing-artifacts-to

Any failing tests will always have their result image written to the result directory – the `mpl-results-always` option just makes it save result images for passing tests also.

The failures on circleci are likely due to different FreeType versions between Windows and (I assume) Linux on circleci – see the end of [this section of the docs](https://pytest-mpl.readthedocs.io/en/latest/usage.html#run-the-image-comparison-tests).

Let us know how you get on!

**Comment by Vital-Fernandez** [comment]
Hello @ConorMacBride! Thank you very much for the detailed reply. I added the following line to the pyproject.toml:

`mpl-results-path = 'tests/outputs'`

And now the tests are done in that folder. 

I have increased the RMS tolerance (until I move to linux) and circleci seems fine now. 

There are two things, however, which I am not sure if it's my fault or there is a bug:

1) If I add the line  

`mpl-results-always = true`

The tests are kept even if false.

2) If I add the line

mpl-default-tolerance = 25

The tolerance (according to circleci) is still 2... I have added it manually to the decorators and it works.

Thank you very much. It is fixed :).

**Comment by ConorMacBride** [comment]
No problem @Vital-Fernandez! Glad to hear that it is now working for you.

If you set `mpl-results-always = true` the result images for passing and failing tests will be saved to your `tests/outputs`. If you set `mpl-results-always = false` only the result images for failing tests will be saved to your `tests/outputs`.

If you have enabled the HTML summary generation, the setting is forced to be `mpl-results-always = true` even if you have disabled it with `mpl-results-always = false`. This lets people see both images and the diff even if a high tolerance is set.

Setting `mpl-default-tolerance = 25` will not work yet because that configuration option hasn't made it into a `pytest-mpl` release. Currently only the decorator setting will work. Thank you for reminding me about this – we'll have to get a `v0.17.0` release out soon!
